version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"

  - package-ecosystem: "maven"
    directory: "/api"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"
      
  - package-ecosystem: "maven"
    directory: "/spec"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"

  - package-ecosystem: "maven"
    directory: "/tck"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"
